import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';

const Custom404: NextPage = () => {
  return (
    <div className="container">
      <Head>
        <title>Penguin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="row">
        <h1 className="text-center">
          404 - Page Not Found
        </h1>
      </main>
    </div>
  );
};

export default Custom404;