import '../styles/styles.scss';
import type {AppProps} from 'next/app';
import {wrapper} from '../app/store';
import {Provider} from 'react-redux';
import Head from 'next/head';
import {Quicksand} from '@next/font/google';

const quicksand = Quicksand();

function MyApp({ Component, ...rest }: AppProps) {
  const {store, props} = wrapper.useWrappedStore(rest);
  return (
    <Provider store={store}>
      <Head>
        <title>Penguin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={quicksand.className}>
        <Component {...props.pageProps} />
      </main>
    </Provider>
  );
}

export default MyApp;
