import { wrapper } from '../app/store';
import {authenticate} from './_app';
import {selectClient} from 'features/auth/authSlice';
import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { useSelector } from 'react-redux';

const Home: NextPage = () => {
  const {token, data} = useSelector(selectClient);


  return (
    <div className="container">
      <Head>
        <title>Penguin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="row">
        <button>{data?.name ?? 's'}</button>
        <p>
          Go to <Link href="/profile">Profile</Link> {token}
        </p>
      </main>
    </div>
  );
};

export default Home;

export const getServerSideProps = wrapper.getServerSideProps(store => async (ctx) => {
  await authenticate(store, ctx);

  return {props: {}};
});
