import { wrapper } from '../app/store';
import {authenticate} from './_app';
import {selectClient} from 'features/auth/authSlice';
import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { useSelector } from 'react-redux';

const Home: NextPage = () => {
  const client = useSelector(selectClient);

  return (
    <div>
      <Head>
        <title>Penguin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button>{client.data.name}</button>
      <p>
        Go to <Link href="/profile">Profile</Link> {client.token}
      </p>
    </div>
  );
};

export const getServerSideProps = wrapper.getServerSideProps(store => async (ctx) => {
  await authenticate(store, ctx);

  return {props: {}};
});

export default Home;
