import { wrapper } from '../app/store';
import { selectProfile, setProfileData } from 'features/profile/profileSlice';
import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { useSelector } from 'react-redux';

const Home: NextPage = (props: any) => {
  const profile = useSelector(selectProfile);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>
        Go to <Link href="/profile">Profile</Link>
      </p>
    </div>
  );
};

export const getServerSideProps = wrapper.getServerSideProps(store => async ({ query }) => {
  store.dispatch(setProfileData('mihai'));
  const data = query.data || 'default data';

  return {
    props: {
      data
    }
  };
});

export default Home;
