import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { useSelector } from 'react-redux';

import { wrapper } from '../app/store';
import { selectProfile } from 'features/profile/profileSlice';

const Profile: NextPage = (props: any) => {
  const profile = useSelector(selectProfile) as any;

  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="row">
        <h1 className="text-center">
          Your Featuring Code, {profile?.name}
        </h1>
        <p>
          Go to <Link href="/">Home</Link>
        </p>

        <p>
          Hello, {props.profileData}!
        </p>
      </main>
    </div>
  );
};

export const getServerSideProps = wrapper.getServerSideProps(() => async ({ query }) => {
  const profileData = query.data || 'profile data';

  return {
    props: {
      profileData
    }
  };
});

export default Profile;
